queue_rules:
  - name: default
    merge_conditions:
      - check-success=Evaluate flake.nix
      - check-success=check basic [x86_64-linux]
      - check-success=check devShell-default [x86_64-linux]
      - check-success=check package-default [x86_64-linux]
      - check-success=check package-nix-ld-rs [x86_64-linux]
      - check-success=devShell default [x86_64-linux]
      - check-success=package default [x86_64-linux]
      - check-success=package nix-ld-rs [x86_64-linux]
defaults:
  actions:
    queue:
      allow_merging_configuration_change: true
      method: rebase
pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
      - label~=merge-queue|dependencies
    actions:
      queue: {}
