[package]
name = "nix-ld"
version = "0.1.0"
authors = ["Jörg Thalheim <joerg@thalheim.io>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = { git = "https://github.com/Mic92/libc", branch = "no-libc" }


[build-dependencies]
cc = "*"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
