[package]
name = "nix-ld"
version = "0.1.0"
authors = ["Jörg Thalheim <joerg@thalheim.io>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[build-dependencies]
cc = "*"

[profile.release]
panic = "abort"
lto = true
