[package]
name = "nix-ld-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-match = "0.2.1"
compiler_builtins = { version = "0.1.93", features = ["mem"] }
goblin = { version = "0.7.1", default-features = false, features = ["elf32", "elf64"] }
heapless = "0.7.16"
log = "0.4.19"

[build-dependencies]
cc = "1.0.79"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = 3
